{
  "openapi": "3.0.1",
  "info":
    {
      "title": "Corca Ads Demo Server",
      "description": "Corca Ads를 사용하는 데모 서버를 위한 API",
      "version": "1.0",
    },
  "servers":
    [{ "url": "http://localhost:8080", "description": "Generated server url" }],
  "tags":
    [
      {
        "name": "Product",
        "description": "광고 상품이 아닌 기존의 상품을 조회하는 데 사용되는 API",
      },
      {
        "name": "Corca Ads",
        "description": "Corca Ads에서 광고 상품을 가져오는 데 사용되는 API",
      },
    ],
  "paths":
    {
      "/api/products":
        {
          "get":
            {
              "tags": ["Product"],
              "operationId": "getProducts",
              "parameters":
                [
                  {
                    "name": "pageable",
                    "in": "query",
                    "description": "페이지 정보",
                    "required": true,
                    "schema": { "$ref": "#/components/schemas/Pageable" },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "OK",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                {
                                  "$ref": "#/components/schemas/PageProductDTO",
                                },
                            },
                        },
                    },
                },
            },
        },
      "/api/products/{productId}":
        {
          "get":
            {
              "tags": ["Product"],
              "summary": "상품 상세 정보",
              "description": "상품 ID를 기반으로 상품 상세 정보를 조회합니다.",
              "operationId": "getProduct",
              "parameters":
                [
                  {
                    "name": "productId",
                    "in": "path",
                    "description": "조회할 상품 ID",
                    "required": true,
                    "schema": { "type": "string" },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "Success",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                { "$ref": "#/components/schemas/ProductDTO" },
                            },
                        },
                    },
                },
            },
        },
      "/api/corca-ads/products":
        {
          "get":
            {
              "tags": ["Corca Ads"],
              "summary": "Corca Ads를 통해 광고 상품을 가져옵니다.",
              "description": "제공된 매개변수에 따라 제안된 광고 상품을 반환합니다.",
              "operationId": "getCorcaAdsProducts",
              "parameters":
                [
                  {
                    "name": "params",
                    "in": "query",
                    "description": "Corca Ads 요청 파라미터",
                    "required": true,
                    "schema":
                      { "$ref": "#/components/schemas/CorcaAdsRequestDTO" },
                  },
                ],
              "responses":
                {
                  "200":
                    {
                      "description": "Success",
                      "content":
                        {
                          "*/*":
                            {
                              "schema":
                                {
                                  "$ref": "#/components/schemas/CorcaAdsProductResponseDTO",
                                },
                            },
                        },
                    },
                },
            },
        },
    },
  "components":
    {
      "schemas":
        {
          "Pageable":
            {
              "type": "object",
              "properties":
                {
                  "page":
                    { "minimum": 0, "type": "integer", "format": "int32" },
                  "size":
                    { "minimum": 1, "type": "integer", "format": "int32" },
                  "sort": { "type": "array", "items": { "type": "string" } },
                },
            },
          "PageProductDTO":
            {
              "type": "object",
              "properties":
                {
                  "totalPages": { "type": "integer", "format": "int32" },
                  "totalElements": { "type": "integer", "format": "int64" },
                  "first": { "type": "boolean" },
                  "last": { "type": "boolean" },
                  "size": { "type": "integer", "format": "int32" },
                  "content":
                    {
                      "type": "array",
                      "items": { "$ref": "#/components/schemas/ProductDTO" },
                    },
                  "number": { "type": "integer", "format": "int32" },
                  "sort": { "$ref": "#/components/schemas/SortObject" },
                  "numberOfElements": { "type": "integer", "format": "int32" },
                  "pageable": { "$ref": "#/components/schemas/PageableObject" },
                  "empty": { "type": "boolean" },
                },
            },
          "PageableObject":
            {
              "type": "object",
              "properties":
                {
                  "offset": { "type": "integer", "format": "int64" },
                  "sort": { "$ref": "#/components/schemas/SortObject" },
                  "pageNumber": { "type": "integer", "format": "int32" },
                  "pageSize": { "type": "integer", "format": "int32" },
                  "paged": { "type": "boolean" },
                  "unpaged": { "type": "boolean" },
                },
            },
          "ProductDTO":
            {
              "type": "object",
              "properties":
                {
                  "id":
                    {
                      "type": "string",
                      "description": "스토어의 데이터베이스에 저장된 상품의 고유 식별자",
                    },
                },
            },
          "SortObject":
            {
              "type": "object",
              "properties":
                {
                  "empty": { "type": "boolean" },
                  "sorted": { "type": "boolean" },
                  "unsorted": { "type": "boolean" },
                },
            },
          "CorcaAdsRequestDTO":
            {
              "required": ["clientId", "deviceId", "placementId", "sessionId"],
              "type": "object",
              "properties":
                {
                  "clientId":
                    {
                      "type": "string",
                      "description": "Corca Ads 서비스의 클라이언트 ID",
                    },
                  "placementId":
                    {
                      "type": "string",
                      "description": "Corca Ads 서비스에서 발급받은 광고가 나갈 지면(구좌) ID",
                    },
                  "sessionId":
                    {
                      "type": "string",
                      "description": "엔드유저가 스토어를 방문하고 있는 동안 유지되는 세션의 고유 식별자",
                    },
                  "deviceId":
                    {
                      "type": "string",
                      "description": "엔드 유저의 디바이스 고유 식별자",
                    },
                  "customerId":
                    {
                      "type": "string",
                      "description": "스토어에 로그인한 엔드유저를 식별하기 위한 값, 로그인 하지 않은 유저는 null로 설정",
                    },
                  "userAgent":
                    {
                      "type": "string",
                      "description": "엔드유저의 User-Agent 정보",
                    },
                },
              "description": "Corca Ads API 요청 DTO",
            },
          "CorcaAdsProductResponseDTO":
            {
              "type": "object",
              "properties":
                {
                  "suggestions":
                    {
                      "type": "array",
                      "description": "광고 제안 목록",
                      "items": { "$ref": "#/components/schemas/SuggestionDTO" },
                    },
                  "placement": { "$ref": "#/components/schemas/PlacementDTO" },
                },
              "description": "Corca Ads 상품 응답 DTO",
            },
          "LogOptionsDTO":
            {
              "type": "object",
              "properties":
                {
                  "requestId": { "type": "string" },
                  "adsetId": { "type": "string" },
                },
              "description": "광고 제안에 대한 성과 추적을 위한 값, 엔드유저 이벤트에 대해 로그 수집 시 사용",
            },
          "PlacementDTO":
            {
              "type": "object",
              "properties":
                {
                  "id": { "type": "string" },
                  "title": { "type": "string" },
                  "displayCount":
                    {
                      "type": "integer",
                      "description": "지면(구좌)에 제안 받을 광고 아이템의 개수",
                      "format": "int32",
                    },
                  "activated": { "type": "boolean" },
                },
            },
          "SuggestionDTO":
            {
              "type": "object",
              "properties":
                {
                  "product": { "$ref": "#/components/schemas/ProductDTO" },
                  "logOptions":
                    { "$ref": "#/components/schemas/LogOptionsDTO" },
                },
              "description": "광고 제안 목록",
            },
        },
    },
}
